### ISSUE TITLE
Issue: repeated treatment display for the same patient

### ISSUE THREAD

**Issue by shajoezhu** [insightsengineering/rlistings#13]
Issue: repeated treatment display for the same patient

For patient `BRA-1/id-141`, it only has "C: Combination", but it is printed twice.

_Originally posted by @shajoezhu in https://github.com/insightsengineering/rlistings/issues/11#issuecomment-1235015836_

**Comment by 6iris6** [comment]
+1

**Comment by gmbecker** [comment]
Should be fixed now, please reopen if you see the problem again.
