### ISSUE TITLE
Issue: Missing treatment

### ISSUE THREAD

**Issue by shajoezhu** [insightsengineering/rlistings#14]
Issue: Missing treatment

For patient `BRA-1/id-236`, "B: Placebo" arm is not displayed

_Originally posted by @shajoezhu in https://github.com/insightsengineering/rlistings/issues/11#issuecomment-1235016366_

**Comment by 6iris6** [comment]
+1

**Comment by gmbecker** [comment]
Should be fixed now please reopen if you see the problem again
