### ISSUE TITLE
Issue: Rendering taking forever

### ISSUE THREAD

**Issue by shajoezhu** [insightsengineering/rlistings#15]
Issue: Rendering taking forever

just call `lsting` from the console takes forever to render, need to trim it with `head(lsting, 20)`

_Originally posted by @shajoezhu in https://github.com/insightsengineering/rlistings/issues/11#issuecomment-1235031133_

**Comment by 6iris6** [comment]
+1

**Comment by gmbecker** [comment]
Looks like this is from a ton of (hopefully unnecessary) data churn in the `make_row_df` method for `listing_df`.
