### ISSUE TITLE
Referential footnotes support and sorting

### ISSUE THREAD

**Issue by Melkiades** [insightsengineering/rlistings#152]
Placeholder while we are waiting for the workaround made by @shajoezhu to work. Eventually, it may be a lot of work, depending on the state of things about ref. footnotes

**Comment by shajoezhu** [comment]
Hi @Melkiades , Referential footnote is not planned in the initial design of rlistings package. hence we already closed the issue in https://github.com/insightsengineering/rlistings/issues/33

I thought @Teninq already applied my suggestions.

**Comment by shajoezhu** [comment]
see https://github.com/insightsengineering/rlistings/issues/176
