### ISSUE TITLE
`fun` argument to `add_listing_col` should probably be deprecated, `na_str` and `align` arguments are untested (but should be kept)

### ISSUE THREAD

**Issue by gmbecker** [insightsengineering/rlistings#218]
The `fun` argument is a very old vestige where we allow the _creation of new columns_ in an existing `listing_df` and the simultaneous setting of them as display columns, but thats not the UX we ultimately went with and I don't think any code is using it.

**Comment by Melkiades** [comment]
I checked the code and even if it is not in our goals I do not see any harm in keeping it. I do not want to disappoint if someone is using it. Closing this for now.
