### ISSUE TITLE
Add page-size machinery to listings pagination to match rtables behavior

### ISSUE THREAD

**Issue by gmbecker** [insightsengineering/rlistings#43]
Look at how rtables transforms page specification (`page_type`, and `pg_width` + `pg_height`, and `font_family` + `font_size`) into lpp (lines per page) and cpp (characters per page) in the pagination machinery, and implement the same in the rlistings pagination machinery.

**Comment by gmbecker** [comment]
Blocked until #60 is merged in as it touches the same functions

**Comment by shajoezhu** [comment]
Hi @gmbecker , can we unblock this issue now?
