### ISSUE TITLE
Design Decision - cols vs key_cols

### ISSUE THREAD

**Issue by gmbecker** [insightsengineering/rlistings#44]
Highlighted by #40 

I'm no longer convinced columns should need to be specified in both `cols` and `key_cols` (Which is, I believe, the underlying cause of the above bug). I'm not sure if it was an intentional decision initially or not, but if it was I'm struggling to remember/understand the reasoning. 

In other words, my thinking now is that 

```
as_listing(iris, cols = c("Petal.Width", "Sepal.Length"), key_cols = c("Species"))
```

should be a valid usage.

I'm also wondering whether a missing/NULL `cols` argument should mean all columns in the incoming data. It seems tedious to specify all the columns if its just all of them anyway.

So then

```
as_listing(iris, key_cols = "Species")
```

would be valid, and creating a listing that included of the columns, with Species as the (only) key column. 

Please consider this and come ready to discuss it our meeting @shajoezhu @Melkiades @edelarua @BFalquet @crazycatandy

**Comment by clarkliming** [comment]
hi @gmbecker I agree with you that key cols should not be included in cols. the default value  for cols can be set to missing and by default all columns except the key cols will be used. The default value for key cols can be set to NULL/character(0) so that no key columns is needed. Then `as_listing(iris)` should also work to display all columns

**Comment by shajoezhu** [comment]
> hi @gmbecker I agree with you that key cols should not be included in cols. the default value for cols can be set to missing and by default all columns except the key cols will be used. The default value for key cols can be set to NULL/character(0) so that no key columns is needed. Then as_listing(iris) should also work to display all columns

agreed!

I think we have a decision now

**Comment by Melkiades** [comment]
There is a thing I do not understand about the standard behavior: if I ask for only one column for example `Species`. Should I get one column with 4-5 unique levels with empty lines to show the "repetition" of the levels (1) or one column like in `data.frame` with repeated values (2), or a column with only the 4-5 unique levels? Atm, `key_cols` variables produce figure (1) while `cols` produces (2). Should we automatically always do (1) and in case where the rows are not unique compact the list as in the third case, by removing repeated values?
(1)
![Screenshot 2022-11-10 110917](https://user-images.githubusercontent.com/11279768/201064275-91bb5544-98c0-439d-b389-26f7d5d8ac73.png)

(2)
![Screenshot 2022-11-10 110859](https://user-images.githubusercontent.com/11279768/201064169-6830b814-7785-4d63-b64a-a301d4cfe8ff.png)

**Comment by Melkiades** [comment]
I used the tests in my (closed) PR and they respond identically now. I believe the expected behavior is respected. Closing this as initial API respects our design decisions
