### ISSUE TITLE
Error when `lpp = NULL`

### ISSUE THREAD

**Issue by Melkiades** [insightsengineering/rlistings#53]
```
> paginate_listing(lsting, lpp = NULL, cpp = 15)
Error in if (adjrlpp <= 0) { : argument is of length zero
```

_Originally posted by @Melkiades in https://github.com/insightsengineering/rlistings/pull/50#discussion_r1019195823_

**Comment by ayogasekaram** [comment]
Waiting for PR from Gabe to see if issue is already resolved with his changes (Monday Dec 12). If not, PR will be changed accordingly.

**Comment by Melkiades** [comment]
Note: this is still an active bug.

**Comment by ayogasekaram** [comment]
Bug has been resolved and closed
https://github.com/insightsengineering/rlistings/pull/60#issuecomment-1360527194
