### ISSUE TITLE
add `export_as_txt` like rtables

### ISSUE THREAD

**Issue by clarkliming** [insightsengineering/rlistings#61]
currently, the export functionality is very limited. To export a paginated listing need extra work of manually call "paginate" and `print` functions. something like `export_as_txt` and ~`export_as_pdf`~ like what we have in rtables are needed.

Joe: discussed with Liming. We will focus on the export_as_txt functionality, and leave txt file to pdf to downstream

**Comment by shajoezhu** [comment]
hi @gmbecker , I was wondering if we could move tt_export.R to formatters, so the exporting functionality could be shared between both rtables and rlistings?

https://github.com/Roche/rtables/blob/df896465b0c62cf610fdf3089dd782d34205bf79/R/tt_export.R

**Comment by gmbecker** [comment]
@shajoezhu doing so is this is in the backlog but not slated for work in this increment.

**Comment by shajoezhu** [comment]
thanks @gmbecker ! backlog please. Let's carry out this in the next PI
