### ISSUE TITLE
rename "prov_footer" to "provence_footer"

### ISSUE THREAD

**Issue by clarkliming** [insightsengineering/rlistings#62]
# motivation

in rtables, we have main_title / subtitles / main_footer/ provence_footer

in rlistings, we have main_title/ subtitles / main_footer / prov_footer

why don't use the same attribute as the rtables?

I know the function name is the same like `prov_footer` but why not make the slots/attributes using the same name? 

# todo

rename "prov_footer" to "provence_footer"

**Comment by clarkliming** [comment]
@shajoezhu instead of rename `prov_footer` to `provence_footer`, maybe we need also make the generic method consistent? the generic name is `prov_footer`

**Comment by gmbecker** [comment]
@clarkliming the reason we provide the function is that users should never be looking at the underlying structure. It is undefined from a user perspective exactly how and where we store the provenance footer information, and is subject to change.

Please ensure *all* your code *only ever* interacts with provenance footer via the provided getter and setter (`prov_footer` and `prov_footer<-`) and the object constructors (`as_listing`, etc). 

Any code that directly accesses the provenance footer (or any) associated attribute on an object directly is unsupported and liable to break without warning.

**Comment by shajoezhu** [comment]
Hi @gmbecker , thanks for the feedback! and we all agree with the approach, I think at the moment, it was just in `rtables` that things were called `provence_footer`, if we can rename this to `prov_footer`, and everyone is happy :) it's should be a small fix. what do you think?

**Comment by clarkliming** [comment]
Hi @gmbecker thank you for your reply. The current situation is, in citril we split the output generation into two steps: 1. you create the output without title/footnote information. 2. add titles/footnotes to it.

The reason to have this is that, we would like to have a consistent approach for all tlgs. plots are decorated with `tern::decorate_grob(set)` after it is generated. In addition, this separation simplifies a little bit about the creation of outputs (so no need to care about the titles and footnotes).

So in the decoration steps, we need to set the titles/footnotes manually. As there are four attributes, we use `slot(object, slotname) <- new_value` currently to reduce the replicated code. With your recommendation, we will either replicate the code for these lines, or obtain the function name from slot name. Do you have any recommendations here?

**Comment by shajoezhu** [comment]
closing this issue. As we have decided to use the setters and getters explicitly
