### ISSUE TITLE
Should we have a `unique = FALSE(default)/TRUE` to show a simplified list?

### ISSUE THREAD

**Issue by Melkiades** [insightsengineering/rlistings#63]
I am blocking this for now as it is out of scope, but in cases (also exploratory) where you have mainly factors, it may be useful to have a simple unique (or unique_rows) variable. To be discussed during planning.

(1)
![Screenshot 2022-11-10 110917](https://user-images.githubusercontent.com/11279768/201064275-91bb5544-98c0-439d-b389-26f7d5d8ac73.png)

(2)
![Screenshot 2022-11-10 110859](https://user-images.githubusercontent.com/11279768/201064169-6830b814-7785-4d63-b64a-a301d4cfe8ff.png)

_Originally posted by @Melkiades in https://github.com/insightsengineering/rlistings/issues/44#issuecomment-1310059939_

**Comment by shajoezhu** [comment]
Think we can close this issue now. and it will be addressed by https://github.com/insightsengineering/rlistings/issues/87
