### ISSUE TITLE
Finalize initial release API

### ISSUE THREAD

**Issue by gmbecker** [insightsengineering/rlistings#72]
- [x] argument naming
- [x] default display-listings behavior
- [x] deprecate/remove fun argument from `add_listing_col`?

This will be implemented as new feature in the next release
- #87

**Comment by gmbecker** [comment]
Specifying formats for columns in a listing. Possible APIs @shajoezhu @Melkiades @crazycatandy @clarkliming @BFalquet @ayogasekaram @edelarua 

Possibility 1:

```
as_listing(mydf, 
                  key_cols = "ARM",
                  disp_cols  = NULL,
                  col_formats = c("<numeric>" = "xx.x", "BMRKR2" = "xx.xx"),
                  col_na_strs = c("<all>" = " - ", "BMRKR2" = "XXX"),
                  col_aligns = c("<char>" = "center", "<numeric>" = "right") ## could do <all> = "center" too
                  )
```

Possibility 2:
```
as_listing(mydf, 
                  key_cols = "ARM",
                  disp_cols = NULL, ## means everything,
                  default_formats = c("numeric" = "xx.x", "character" = "xx"),
                  default_na_strs = c("ALL" = "-"),
                  default_aligns = c("character" = "center", numeric = "right")
                  col_formats = c("BMRKR2" = "xx.xx"),
                  col_na_strs = c("BMRKR2" = "XXX"),
                  col_aligns = c("BMRK2" = "left") 
                  )
```

Possibility 3: 
```
mycfg <- fmt_config(format = "xx", na_str = "-", align = "center")
mycfg2 <- fmt_config(format = "xx.x", na_str = "-", align = "center")
mycfg3<- fmt_config(format = "xx.xx", na_str = "XX", align = "right")

as_listing(mydf, 
                  key_cols = "ARM",
                  disp_cols = NULL, ## means everything,
                  col_formatting = list("<all>" = mycfg, "<numeric>" = mycfg2,  BMRKR2 = mycfg3))
                  )
```

Possibility 4: joint default argument
```
mycfg <- fmt_config(format = "xx", na_str = "-", align = "center")
mycfg2 <- fmt_config(format = "xx.x", na_str = "-", align = "center")
mycfg3<- fmt_config(format = "xx.xx", na_str = "XX", align = "right")
as_listing(mydf, 
                  key_cols = "ARM",
                  disp_cols = NULL, ## means everything,
                  default_formatting = list("<all>" = mycfg,  "numeric" = mycfg2)
                  col_formatting = list(BMRKR2 = mycfg3))
                  )
```

**Comment by Melkiades** [comment]
Reading again the possibilities after the meeting I find possibility 3 the most compact and elegant. It needs a bit of learning for the user so to start using formatting objects like `fmt_config`. If we want to be more plain option 4 or 2 fits our need but I am a strong supporter of minimizing the number of parameters for as_listings. In general, I would use always `<numeric>` instead of 'numeric' for type-format assignments

**Comment by shajoezhu** [comment]
Let's also discuss the following options please

Possibility 5: minimal default, and setting externally after the initial call
```
init_lst <- as_listing(mydf, 
                  key_cols = "ARM",
                  disp_cols = NULL, ## means everything,
                  default_formats = c("numeric" = "xx.x", "character" = "xx"),
                  default_na_strs = c("ALL" = "-"),
                  default_aligns = c("character" = "center", numeric = "right")

init_lst %>% 
  set_col_format(cols = c('a','b'), format = 'xx.xx', na_str = ' - ') %>%
  set_col_format(cols = c('c','d'), format = 'xx.x%', na_str = ' NA ')
```

Possibility 6: minimal default, and setting externally after the initial call
```
init_lst <- as_listing(mydf, 
                  key_cols = "ARM",
                  disp_cols = NULL, ## means everything,
                  default_formats = c("numeric" = "xx.x", "character" = "xx"),
                  default_na_strs = c("ALL" = "-"),
                  default_aligns = c("character" = "center", numeric = "right")

init_lst %>% 
 set_col_formats (c("BMRKR2" = "xx.xx")) %>%,
 set_col_na_strs(c("BMRKR2" = "XXX")) %>%
 set_col_align(c("BMRKR2" = "right"))
```

Possibility 7: minimal default, and setting externally after the initial call
```
init_lst <- as_listing(mydf, 
                  key_cols = "ARM",
                  disp_cols = NULL, ## means everything,
                  default_formats = c("numeric" = "xx.x", "character" = "xx"),
                  default_na_strs = c("ALL" = "-"),
                  default_aligns = c("character" = "center", numeric = "right")

for ( conf_i in some_format_att_list ){
    init_list <- init_list %>% set_col_format_att(conf_i)
}

where conf_i can be a list as 

$var
  "BMRKR2"
$format
  "xx.xx"
$na_str
  " - "
$align
  "right"
```

**Comment by gmbecker** [comment]
@shajoezhu we can discuss these more but currently I'm leaning pretty strongly against any API that *requires* postprocessing for the object to be useful, which these all would in many cases. 

If you can set some formatting information in the `as_listing` call, it really seems like you should be able to set all of it

**Comment by shajoezhu** [comment]
thansk a lot @gmbecker. tagging @barnett11 and @khatril as well, to review this from user perspective

**Comment by barnett11** [comment]
I personally like 3 or 4, not much difference in either for myself - If I have an additional column I'd like to define all the information together in one place as done in 3/4 rather than splitting across different inputs

**Comment by khatril** [comment]
I would opt for a more compact option such as 3 or 4.

**Comment by shajoezhu** [comment]
between 3 and 4, I prefer 4. more explicit, and easy to read

**Comment by gmbecker** [comment]
Alright so it looks like we have a consensus that we want one of the two APIs that use `fmt_config` (name subject to possible change).

I agree I think this is the better way as well, but it will take a bit of doing. I will file and then work on an issue in `formatters` (which is the only reasonable place for `fmt_config` to live)

Once that exists, `rtables` should also support it (both for consistency and for the same reasons we're doing it here), so we will add that to the PI planning for the upcoming increment.
