### ISSUE TITLE
All columns displayed with add_listing_col

### ISSUE THREAD

**Issue by Nolan-Steed** [insightsengineering/rlistings#77]
When `add_listing_col` is added to a listing and the `disp_cols` is `NULL`, all of the columns are still shown in the listing. Should only the `key_cols` and `add_listing_cols` be displayed?
```
dat <- ex_adae

lsting <- as_listing(dat[1:25, ], key_cols = c("USUBJID", "AESOC"), disp_cols = NULL) %>%
  add_listing_col("AETOXGR") %>%
  add_listing_col("BMRKR1", format = "xx.x") %>%
  add_listing_col("AESER / AREL", fun = function(df) paste(df$AESER, df$AREL, sep = " / "))

mat <- matrix_form(lsting)

cat(toString(mat))
```

**Comment by gmbecker** [comment]
@Nolan-Steed It was decided, primarliy between @shajoezhu, @crazycatandy and myself, that the api would be that `NULL` for the disp columns means all of them. That conversion happens at `as_listing` time, so by the time you're calling `add_listing_col` all of the columns are already specified as listing columns

You should be able to do `disp_cols = character()` if you want to start with none of them and build up using the `add_listing_col` API, which as of now is currently still supported.

**Comment by Nolan-Steed** [comment]
I see, thanks @gmbecker
