### ISSUE TITLE
page number implementation

### ISSUE THREAD

**Issue by shajoezhu** [insightsengineering/rlistings#80]

**Comment by gmbecker** [comment]
This belongs in formatters @shajoezhu can we close it here?

**Comment by shajoezhu** [comment]
Hi Gabe, do you mean we already have machinary in formatters can do that? and rtables is using the same thing?

**Comment by gmbecker** [comment]
No but the development of the feature would happen in formatters, not in rlistings

**Comment by shajoezhu** [comment]
Hi Gabe, shouldn't that be part of paginationation?

**Comment by gmbecker** [comment]
Pagination currently doesn't support the tracking and rendering of page numbers. Its a feature on the roadmap, but hasn't been prioritized in PI planning. But when it is implemented, it will be implemented in matrix-print-form/pagination/rendering which all live in `formatters`
