### ISSUE TITLE
pagebreak 

### ISSUE THREAD

**Issue by shajoezhu** [insightsengineering/rlistings#81]
- \s\n replace to \f

**Comment by gmbecker** [comment]
Blocked pending discussion after the upcoming release

**Comment by shajoezhu** [comment]
unblock this as discussed, the release will happen towards end of March.

**Comment by gmbecker** [comment]
@shajoezhu this is stills omething that is blocked on us having a discussion about it. We should leave the blocked tag on so that someone doesn't just do it before that happens...

**Comment by shajoezhu** [comment]
closing this now. we will refine this request with another related topic

**Comment by gmbecker** [comment]
Closing this as we discussed it and eventually agreed it was not desirable.
