### ISSUE TITLE
move test dsl01 out of rlisting to scda.test

### ISSUE THREAD

**Issue by shajoezhu** [insightsengineering/rlistings#86]

**Comment by gmbecker** [comment]
@shajoezhu @Melkiades this should be reverted. The test did not depend on scda, but rather on formatters::ex_adsl, and there wasn't any reason to remove it; reducing tests should only happen when there is a good reason (e.g., the feature being tested has been removed, the test takes too long and can't beoptimized, etc).

**Comment by shajoezhu** [comment]
Happy to leave this issue open for now if more discussion is needed.

**Comment by shajoezhu** [comment]
hey @gmbecker , following our discussion this morning. We can close issue now right?
