### ISSUE TITLE
specifying formats, alignment, etc, especially in `as_listing`

### ISSUE THREAD

**Issue by shajoezhu** [insightsengineering/rlistings#87]
Please refer to https://github.com/insightsengineering/rlistings/issues/72 for the discussion

4 possibility was proposed at 

https://github.com/insightsengineering/rlistings/issues/72#issuecomment-1358724037

where, option 4 is the most favored.

Possibility 4: joint default argument
```r
mycfg <- fmt_config(format = "xx", na_str = "-", align = "center")
mycfg2 <- fmt_config(format = "xx.x", na_str = "-", align = "center")
mycfg3<- fmt_config(format = "xx.xx", na_str = "XX", align = "right")
as_listing(mydf, 
                  key_cols = "ARM",
                  disp_cols = NULL, ## means everything,
                  default_formatting = list("<all>" = mycfg,  "numeric" = mycfg2)
                  col_formatting = list(BMRKR2 = mycfg3))
                  )
```

More comment from Gabe:

> Alright so it looks like we have a consensus that we want one of the two APIs that use fmt_config (name subject to possible change).
> 
> I agree I think this is the better way as well, but it will take a bit of doing. I will file and then work on an issue in formatters (which is the only reasonable place for fmt_config to live)
> 
> Once that exists, rtables should also support it (both for consistency and for the same reasons we're doing it here), so we will add that to the PI planning for the upcoming increment.

**Comment by Melkiades** [comment]
Maybe we should address this along with the unique considerations @shajoezhu @Nolan-Steed

**Comment by Nolan-Steed** [comment]
I was recently trying to develop a rlisting and I agree with @Melkiades that it doesn't make sense to include empty rows in the listing which is demonstrated in issue #63. It would be nice to have `unique` argument which defaults to removing blank rows.
