### ISSUE TITLE
import export_as_txt from formatters, and remove the current rlstings export_as_txt, use staged dependencis 96_exporter_pagination_migration

### ISSUE THREAD

**Issue by shajoezhu** [insightsengineering/rlistings#96]
@clarkliming This could be a generic, though honestly it should be a function in formatters which invokes generics  along the lines of (pseudocode)

```
export_as_txt <- function(obj, file, page_type, ...) {
     paged <- paginate(obj, page_type, ...)
     
     unlink(file)
     lapply(paged, function(x) cat(toString(x), file = file, sep = page_break, append = TRUE)
}
```

The thing missing for the above to work is that `paginate` should be a generic, rather than a differently named function for each package (ie `paginate_table` and `paginate_listing`) Easy to do, but it is an API change so we'd need to do a deprecation cycle of the old versions...

_Originally posted by @gmbecker in https://github.com/insightsengineering/rlistings/pull/95#discussion_r1115978823_
            

# TODO

please also check

- [x] https://github.com/insightsengineering/rlistings/blob/main/R/rlistings-package.R#L8
- [x] https://github.com/insightsengineering/rlistings/blob/main/R/rlistings-package.R#L9

**Comment by gmbecker** [comment]
@shajoezhu this should be an issue in formatters, not rlistings
