### ISSUE TITLE
first cran release (targeting cran release out by 17th-March-2023)

### ISSUE THREAD

**Issue by shajoezhu** [insightsengineering/rlistings#99]
- [x]  increase versioned dependency on formatters to >=0.4.0
- [x]  Bump version to 0.2.1
- [x]  Submit to CRAN
- [x]  Respond to CRAN feedback
- [x]  Accepted on CRAN
- [x]  merge cran_release_0.2.1 into main
- [x]  tag github release 0.2.1
- [x] update citril DESCRIP5TION of  rlistings >= 0.2.1 https://github.com/insightsengineering/citril/issues/209
- [x]  update chevron DESCRIPTION of rlistings >= 0.2.1 https://github.com/insightsengineering/chevron/issues/455

**Comment by gmbecker** [comment]
@shajoezhu items in this issue were in order. Why was the tag created before 0.2.0 was _accepted_ on CRAN? If we need to revise based on CRAN feedback, what are we going to do?

**Comment by gmbecker** [comment]
CRAN version will be 0.2.1 due to needing to revise based on CRAN feedback. New tag will be required.

**Comment by gmbecker** [comment]
Passed auto checks, waiting for final acceptance.

**Comment by shajoezhu** [comment]
> @shajoezhu items in this issue were in order. Why was the tag created before 0.2.0 was accepted on CRAN? If we need to revise based on CRAN feedback, what are we going to do?

There is also downstream dependencies on this. This was the plan B if CRAN release was not completed by Friday.

**Comment by gmbecker** [comment]
Sure but that could have waited until friday since tagging in gitub takes like 10 seconds...

**Comment by gmbecker** [comment]
CRAN release of v0.2.1 complete. reassigning to @shajoezhu for updates to reverse deps.
